### ISSUE TITLE
The example.ipynb not working

### ISSUE THREAD

**Issue by lcorcodilos** [cabinetry/cabinetry-tutorials#8]
Hello,

I've attempted to replicate the example.ipynb tutorial on my own machine and I've run into a few issues. The first, which I solved, was that the Luminosity systematic needs "Samples" to be defined so I added 

```YAML
Samples:
      - "Background"
      - "Signal"
```

This seems to get things going but then I run into the following traceback:

```
Traceback (most recent call last):
  File "example.py", line 17, in <module>
    fit_results = cabinetry.fit.fit(model, data)
  File "/home/lucas/CMS/CabinetryTesting/cabinet-env/lib/python3.6/site-packages/cabinetry/fit.py", line 395, in fit
    model, data = model_utils.model_and_data(spec, asimov=asimov)
  File "/home/lucas/CMS/CabinetryTesting/cabinet-env/lib/python3.6/site-packages/cabinetry/model_utils.py", line 27, in model_and_data
    workspace = pyhf.Workspace(spec)
  File "/home/lucas/CMS/CabinetryTesting/cabinet-env/lib/python3.6/site-packages/pyhf/workspace.py", line 287, in __init__
    super(Workspace, self).__init__(spec, channels=spec['channels'])
TypeError: 'Model' object is not subscriptable
```

I dropped into workspace.py and tried to print `spec['channels']` which seems to work except the traceback then moves to the new print line. So it must be an issue with `spec['channels']` but it's not clear where.

Any help would be appreciated. Thanks!

**Comment by alexander-held** [comment]
Hi @lcorcodilos, thanks for checking out `cabinetry`! From the traceback I see that you are using Python 3.6. `cabinetry` dropped support for Python 3.6 with release [`v0.2.0`](https://github.com/alexander-held/cabinetry/releases/tag/v0.2.0) (in line with `numpy`, which dropped support for 3.6 in [June 2020](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule)).

When you install `cabinetry` with Python 3.6, you will therefore get the last version that still supports Python 3.6, which is `v0.1.8`. The change you observed, where the samples need to be specified for modifiers, is needed in that older version but not in more recent versions (implemented in https://github.com/alexander-held/cabinetry/pull/218). I am not sure yet what causes the `TypeError` you see, but I suspect it is also due to API changes in `cabinetry` or `pyhf`. The current version of the notebooks in this repository is for the (currently) latest version `v0.2.3` of `cabinetry`.

I would recommend working in an environment with Python 3.7+. That resolves the above issue, and will also allow you to use more recent `pyhf` versions (`pyhf` also dropped support for Python 3.6). The last version of this repository that should be compatible with Python 3.6 is [`539cebc`](https://github.com/cabinetry/cabinetry-tutorials/tree/539cebcf3cb6036d5ca3704880f6645d1ed88ee4).

**Comment by lcorcodilos** [comment]
Hi @alexander-held , thanks for the quick response! I've switched my virtualenv to python 3.8 and tried again.

I have two follow ups. First, does dropping `Samples` imply that the systematic is applied to all non-data samples? Second, I now get a new traceback repeated many times. I copy just one instance here:

```
Exception ignored in: <function WeakMethod.__new__.<locals>._cb at 0x7f7d5c476c10>
Traceback (most recent call last):
  File "/usr/lib/python3.8/weakref.py", line 58, in _cb
  File "/usr/lib/python3.8/weakref.py", line 74, in __eq__
TypeError: isinstance() arg 2 must be a type or tuple of types
```

Simply commenting out everything and uncommenting line-by-line shows that the crash is caused by:
```python
model, data = cabinetry.model_utils.model_and_data(ws)
```

Any ideas?

**Comment by alexander-held** [comment]
> First, does dropping Samples imply that the systematic is applied to all non-data samples?

Yes, if you do not specify that option then the modifier (systematic or normalization factor) will be applied to all samples (other than data, on which modifiers are never applied in the HistFactory model). The [documentation](https://cabinetry.readthedocs.io/en/latest/config.html#systematic) mentions the default behavior, but might not be very readable yet.

> traceback repeated many times

This is due to an interaction of `pyhf` and `click`, see https://github.com/scikit-hep/pyhf/issues/1506. There is an open pull request (https://github.com/scikit-hep/pyhf/pull/1530) in `pyhf` to fix this. In the meantime, what you can do is running
```
pip install click~=7.0
```
after you installed `cabinetry`. That will downgrade `click` and avoid the issue, without any impact on functionality. With the next release of `pyhf` this should be solved again, there is nothing we can do from the `cabinetry` side.

**Comment by alexander-held** [comment]
#9 added a bit of text to the readme to describe versions of `cabinetry` and Python compatible with the tutorials in this repository.

**Comment by lcorcodilos** [comment]
Thanks for the explanations and updating the readme. I can confirm this fixed my issues!
